services:
  db:
    image: postgres:17
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
    ports:
      - "5432:5432"

volumes:
  db_data:
